Fixed connection via domain name and consolidated methods
SubnauticaNitrox/Nitrox pull request #1272
Opened 2020-10-31 20:18 UTC by Coding-Hen

Fixed overlooked error with hostnames being picked up by the regex but not resolving the ip address

2020-10-31 22:24 UTC, Measurity requested changes

2020-11-21 22:47 UTC, Measurity requested changes
As discussed in Discord.

Add extra field to "Add server" prompt for port (fill out port as 11000 by default).
Change server save format to store ip and port separately.

2020-11-23 15:11 UTC, dartasen commented on NitroxClient/MonoBehaviours/Multiplayer.cs
> -            Log.InGameLogger = new SubnauticaInGameLogger();
Not sure to understand why you did remove this logger init ?

2020-11-23 17:08 UTC, Measurity approved these changes
Works nicely.

Only minor thing that Log.InGameLogger init is better suited in `NitroxPatcher.Main.Execute` or close to it than hidden away in MainMenuMultiplayerPanel: https://github.com/SubnauticaNitrox/Nitrox/pull/1272/files#diff-8b008cc9cc06ae159843c594eb48d03feea944f2b508d1c57b39cc7326f41b75R37

2020-11-23 20:36 UTC, Measurity approved these changes

2020-11-23 20:37 UTC, dartasen approved these changes

2020-11-24 04:45 UTC, merged