Added EntityData.nitrox to zip backup
SubnauticaNitrox/Nitrox pull request #1374
Opened 2021-01-08 22:42 UTC by ProjectPatatoe

EntityData was not being added in backup zip

2021-01-08 22:54 UTC, dartasen approved these changes

2021-01-08 22:55 UTC, dartasen commented
Maybe It should be better to add every file inside the save dir, so we don't need to maintain this area everytime the save format is changed

2021-01-08 23:18 UTC, ProjectPatatoe commented
yea thats a good idea. I'll change that.

2021-01-08 23:28 UTC, ProjectPatatoe commented
I made it for any .nitrox because an existing zip would be included. If we want to change where the zip is saved then it would make sense to grab the entire directory.

2021-01-08 23:31 UTC, Coding-Hen approved these changes

2021-01-08 23:38 UTC, Jannify requested changes

2021-01-08 23:38 UTC, Jannify commented on NitroxServer/Serialization/World/WorldPersistence.cs
> +                    string[] nitroxFiles = Directory.GetFiles(saveDir, "*.nitrox");
That doesn't include json files if used (see `fileEnding`).

2021-01-09 03:07 UTC, Jannify approved these changes

2021-01-09 07:45 UTC, dartasen approved these changes

2021-01-09 10:01 UTC, Coding-Hen approved these changes

2021-01-09 10:31 UTC, Measurity approved these changes

2021-01-11 02:58 UTC, merged