Nitrox Public API v0
SubnauticaNitrox/Nitrox pull request #1386
Opened 2021-01-13 13:00 UTC by diabolical17

This puts down the infrastructure of the Nitrox Public API.

## Infomation

The Nitrox Public API is a public API that runs on `http://{ServerNumericalIP}:3000/` and includes various endpoints to collect data or interact with your Nitrox Server.

## Spec

The NPAPI is built using Grapevine, a not very well known library that uses Attributes to register methods.

Example:

```cs
[RestRoute("Delete", "/server/stop")]
public async Task stopServer(IHttpContext ctx) {
    Server srv = Server.Instance;
    if (ctx.Request.Headers.Get("Auth") != srv.GetServerConfig().AdminPassword) {
        ctx.Response.StatusCode = 401;
        await ctx.Response.SendResponseAsync(JsonConvert.SerializeObject(new UnauthorizedResponse("Please pass your ADMIN PASSWORD through the Auth header to access this endpoint."), Formatting.Indented));
    } else {
        await ctx.Response.SendResponseAsync(JsonConvert.SerializeObject(new ServerStoppedResponse(), Formatting.Indented));
        srv.Stop();
    }
}
```

These Attributes allow easy addition of more methods, allowing the API to be updated easily.

## Usages

Although you may not be able to think of many usages, here is a wide range:

- Discord Bots
- Website Integrations 
	+ Show currently online players on your website or etc.
- Future Nitrox Usages
	+ Public serverlist?
	+ Paid Hosting?
	+ Web Admin Panels?

## Documentation and Access

The server is automatically ran when the `NitroxServer-Subnautica.exe` is executed. It can be stopped using the `/api stop` and restarted using the `/api start` commands.

Documentation: [TBD]

2021-01-13 13:36 UTC, diabolical17 commented
Discussion from Discord:

![](https://iili.io/KDGAuV.png)

2021-01-14 00:41 UTC, Jannify requested changes

2021-01-14 00:41 UTC, Jannify commented on NitroxServer/Communication/NetworkingLayer/NitroxServer.cs
> +
We use Autofac to get these objects.
Eg. `NitroxServiceLocator.LocateService<PlayerManager>();` or with parameters and initializing it with Autofac (see [here](https://github.com/SubnauticaNitrox/Nitrox/blob/c7dc535fc8658edb220363ba68fb5fab2675a3d6/NitroxServer/ServerAutoFacRegistrar.cs#L33)).

So pls remove any unnecessary getter/setter and use one of the options above.

2021-01-14 00:41 UTC, Jannify commented on NitroxServer/ConsoleCommands/APICommand.cs
> +        }
Duplicate: See [WebHelper.cs](https://github.com/SubnauticaNitrox/Nitrox/blob/master/NitroxModel/Helper/WebHelper.cs)

2021-01-14 00:41 UTC, Jannify commented on NitroxServer/Server.cs
> +        public bool Paused { get; private set; }
Minor: Move up to the other fields/properties.

2021-01-14 01:23 UTC, closed without merging