Basic Banning Implementation
SubnauticaNitrox/Nitrox pull request #1428
Opened 2021-02-27 02:45 UTC by Kantanomo

Added very basic server banning based off a file in the root directory called "Player Bans.txt" the file can be modified and loaded if the server is closed. Otherwise two commands have been added to manage it "ban" and "unban". The command "ban" can be used if the client is connected or not connected to the server. If connected the server owner can use the command to ban them by username, otherwise they can use the IP. the unban command can only be used with the IP address.

NitroxServer.Communication.Packets.Processors.MultiplayerSessionReservationRequestProcessor
To append the IP to the reservation request.

 NitroxServer.Communication.NetworkingLayer.LiteNetLib.LiteNetLibServer 
 Adds a condtion that checks if the IP Is in the ban list

Added IPBanning.cs
A static class used for managing bans
Runs at NitroxServer.Server construction
-- Banning.IpBanning.Load();

Adds two console commands
Ban (player/IP)
unban (player/ip)

These commands modify a file created at runtime in the root directory
Player bans.txt

2021-03-19 17:58 UTC, Jannify requested changes
Sry that the review took so long, after a few days it just slipped my thoughts :D
I have marked a few places where I think there are better solutions. In most cases it's probably because you don't know the code base well yet ;), but that comes with time and is probably also due to the poor and outdated docs.

2021-03-19 17:58 UTC, Jannify commented on NitroxServer/Banning/IpBanning.cs
> +        public static string BanFilePath { get; } = Path.GetFullPath(Path.Combine(Environment.GetEnvironmentVariable("NITROX_LAUNCHER_PATH") ?? "", "Player Bans.txt"));
Maybe get the launcher path from [NitroxModel/Helper/NitroxAppData.cs.](https://github.com/SubnauticaNitrox/Nitrox/blob/master/NitroxModel/Helper/NitroxAppData.cs)

2021-03-19 17:58 UTC, Jannify commented on NitroxServer/Banning/IpBanning.cs
> +    public static class IpBanning
Maybe make a interface (with a shared method "IsBanned") for more banning options in the future and instantiate it with AutoFac (no static class)

2021-03-19 17:58 UTC, Jannify commented on NitroxServer/Banning/IpBanning.cs
> +
Minor: Blank line

2021-03-19 17:58 UTC, Jannify commented on NitroxServer/Communication/NetworkingLayer/LiteNetLib/LiteNetLibServer.cs
> +            if (server.PeersCount < maxConn && !Banning.IpBanning.BannedIPs.Contains(request.RemoteEndPoint.Address.ToString()))
Better to move the check to the class

2021-03-19 17:58 UTC, Jannify commented on NitroxServer/Communication/Packets/Processors/MultiplayerSessionReservationRequestProcessor.cs
> +            Log.Info($"Reservation processed successfully: Username: {packet.AuthenticationContext.Username} - {reservation} - IP Address: {connection.Endpoint.Address.ToString()}");
We don't want to write the IP address to the log files for security reasons, so if you think logging the address is needed here use "InfoSensitive" and refer to examples in our code base for implementation.

2021-03-19 17:58 UTC, Jannify commented on NitroxServer/ConsoleCommands/BanIpCommand.cs
> +        public BanIpCommand(PlayerManager playerManager, EntitySimulation entitySimulation) : base("ban", Perms.MODERATOR, "ban a player from the server", true)
Minor:
```suggestion
        public BanIpCommand(PlayerManager playerManager, EntitySimulation entitySimulation) : base("ban", Perms.MODERATOR, "Bans a player from the server", true)
```

2021-03-19 17:58 UTC, Jannify commented on NitroxServer/ConsoleCommands/BanIpCommand.cs
> +                    {
To reduce duplicated code (L38-47 and L58-L66) I would prefer restricting the if to finding the player-object/address.

2021-03-19 17:58 UTC, Jannify commented on NitroxServer/ConsoleCommands/BanIpCommand.cs
> +                }
Maybe just call `KickCommand.Execute()`? You can get the object with AutoFac.

2021-03-19 17:58 UTC, Jannify commented on NitroxServer/ConsoleCommands/UnBanPlayer.cs
> +        public UnBanIpCommand(PlayerManager playerManager, EntitySimulation entitySimulation) : base("unban", Perms.MODERATOR, "unban a player from the server", true)
Minor:
```suggestion
        public UnBanIpCommand(PlayerManager playerManager, EntitySimulation entitySimulation) : base("unban", Perms.MODERATOR, "Unbans a player from the server", true)
```

2021-03-19 17:58 UTC, Jannify commented on NitroxServer/ConsoleCommands/UnBanPlayer.cs
> +                Player player = args.Get<Player>(0);
There are many places where you check if the IP is valid or not. Maybe move that to `AddNewBan()`/`RemoveBan()` of `IpBanning.cs`.

2021-05-11 11:50 UTC, dartasen commented
Looks like this code will not be maintained by the author, also the code is not in a good state to be merged in our code base.
I'm closing it for now.

2021-05-11 11:50 UTC, closed without merging