Fixed more than one player using a Bench/Chair
SubnauticaNitrox/Nitrox pull request #1440
Opened 2021-03-29 19:44 UTC by Coding-Hen

Fixes #1345

2021-05-09 08:17 UTC, dartasen approved these changes
Looks good to me, I just have a little thing to say about consistency, those are a bit mixed up in the PR :
* `class `  =>  `public class`
* TARGET_CLASS & TARGET_METHOD => TARGET_CLASS merged into TARGET_METHOD

2021-05-09 10:46 UTC, Coding-Hen commented
Good catch will switch them both to the same

2021-05-14 19:58 UTC, Jannify requested changes
This pr will just add the lock not sync the animation, am I right?

2021-05-14 19:58 UTC, Jannify commented on NitroxPatcher/Patches/Dynamic/Bench_ExitSittingMode_Patch.cs
> +    class Bench_ExitSittingMode_Patch : NitroxPatch, IDynamicPatch
```suggestion
    public class Bench_ExitSittingMode_Patch : NitroxPatch, IDynamicPatch
```

2021-05-14 19:58 UTC, Jannify commented on NitroxPatcher/Patches/Dynamic/Bench_OnHandClick_Patch.cs
> +    class Bench_OnHandClick_Patch : NitroxPatch, IDynamicPatch
```suggestion
    public class Bench_OnHandClick_Patch : NitroxPatch, IDynamicPatch
```

2021-05-14 20:11 UTC, Coding-Hen commented
> 
> 
> This pr will just add the lock not sync the animation, am I right?

Yes no animation sync just locking to deny multiple people using the same chair/bench

2021-06-07 12:29 UTC, Jannify approved these changes

2021-06-18 16:15 UTC, merged