Project wide spring cleanup
SubnauticaNitrox/Nitrox pull request #1553
Opened 2021-07-31 20:08 UTC by Jannify

Clean up all cs files with VS internal clean up solution:
- Add/remove braces for single-line control statements
- Sort accessibility modifiers
- Apply expression/block body preferences
- Apply inline 'out' variables preferences
- Format document
- Remove unnecessary usings
- Sort usings
- Apply file header preferences

----

Cleaned up csproj file with [organize-csproj](https://www.nuget.org/packages/organize-csproj)

2021-07-31 20:27 UTC, Measurity requested changes
I would prefer csproj files to not change. Overall looks pretty good.

2021-07-31 20:27 UTC, Measurity commented on NitroxClient/NitroxClient.csproj
> +  <ItemGroup Label=".cs files">
Unnecessary comment added

2021-07-31 20:27 UTC, Measurity commented on NitroxLauncher/NitroxLauncher.csproj
> +    <Compile Include="MainWindow.xaml.cs">
This file has been changed massively. I would prefer to not change csproj files in the PR.

2021-07-31 20:27 UTC, Measurity commented on NitroxModel/DataStructures/GameLogic/NitroxMatrix4x4.cs
>          }
This file should not be changed because Killzoms is working on it.

2021-07-31 20:27 UTC, Measurity commented on NitroxModel/Logger/Log.cs
> +            }
Unnecessary change

2021-07-31 23:45 UTC, Coding-Hen requested changes
Are we able to add any of these rules to say the editor config to ensure compliance going forward and remove the need for a later repeated clean

2021-07-31 23:45 UTC, Coding-Hen commented on NitroxClient/GameLogic/Bases/BuildThrottlingQueue.cs
> +            Log.Info("Enqueuing base piece to be placed techtype: " + basePiece.TechType + " id: " + basePiece.Id + " parentId: " + basePiece.ParentId.OrElse(null) + " build index: " + basePiece.Buil
Switch to consistent style, might want to check this is write as written on mobile 
```suggestion
            Log.Info($"Enqueuing base piece to be placed techtype: {basePiece.TechType} id: {basePiece.Id} parentId: {basePiece.ParentId.OrElse(null)} build index: {basePiece.BuildIndex}");
```

2021-08-01 06:57 UTC, Jannify commented
These rules are more or less in the vs config and are normally applied (at least I enabled that) if you save a file.

2021-08-01 10:34 UTC, Measurity approved these changes

2021-08-01 10:50 UTC, Coding-Hen approved these changes

2021-08-01 10:55 UTC, merged