Add OnEnable and OnDisable to NitroxEntity
SubnauticaNitrox/Nitrox pull request #1579
Opened 2021-08-30 03:18 UTC by killzoms

This theoretically should help with some pointless log spam

2021-08-30 10:55 UTC, dartasen requested changes

2021-08-30 10:55 UTC, dartasen commented on NitroxClient/MonoBehaviours/NitroxEntity.cs
> +            }
Maybe we should log this happy case if it shouldn't happen ?

2021-08-30 10:55 UTC, dartasen commented on NitroxClient/MonoBehaviours/NitroxEntity.cs
> +            }
same here

2021-08-30 10:57 UTC, Measurity commented
Does this have to do with serialization that skips this ID? If we know what's causing it then it should have a comment in code.

2021-09-24 09:38 UTC, Measurity commented
TODO: Verify that this won't prematurely unassign the Nitrox ID (i.e. object is still needed somewhere by our code) when said object is far away.

2021-11-14 14:35 UTC, Measurity commented
Can we move this code to OnDestroy instead?

2021-11-14 15:15 UTC, killzoms commented
@Measurity done

2021-11-14 15:53 UTC, Jannify commented on NitroxClient/MonoBehaviours/NitroxEntity.cs
> +
```suggestion
        public void OnEnable()
        {
            if (Id == null)
            {
                Log.Error($"Nitrox Id was null on {gameObject.name} in OnEnable");
                return;
            }

            gameObjectsById[Id] = gameObject;
        }

        public void OnDestroy()
        {
            if (Id == null)
            {
                Log.Error($"Nitrox Id was null on {gameObject.name} in OnDestroy");
                return;
            }

            gameObjectsById.Remove(Id);
        }
```

2021-11-16 13:20 UTC, Jannify approved these changes

2021-11-16 13:21 UTC, merged