Fix rocket stages and preflight checks bugs
SubnauticaNitrox/Nitrox pull request #1658
Opened 2021-11-29 22:57 UTC by tornac1234

- Check for null PreflightChecks
- Prevent a client from sending back the event of completing a preflight check

2021-11-29 22:57 UTC, tornac1234 commented
Does it finally fix [Issue#1471](https://github.com/SubnauticaNitrox/Nitrox/issues/1471) ?

2021-11-29 23:08 UTC, Jannify requested changes

2021-11-29 23:08 UTC, Jannify commented on NitroxClient/Communication/Packets/Processors/RocketPreflightCompleteProcessor.cs
> +            packetSender ??= NitroxServiceLocator.LocateService<IPacketSender>();
You can get assign the packetSender in a constructor in this class.

2021-11-29 23:08 UTC, Jannify commented on NitroxClient/Communication/Packets/Processors/RocketPreflightCompleteProcessor.cs
> +        private IPacketSender packetSender;
With the construtor:
```suggestion
        private readonly IPacketSender packetSender;
        
```

2021-12-09 13:19 UTC, Measurity commented
Is there a reason we don't just instantiate the PreflightChecks so it's never null? 
Example:
```cs
        [ProtoMember(3)]
        public ThreadSafeList<PreflightCheck> PreflightChecks { get; set; } = new();
```

2021-12-09 16:01 UTC, Measurity approved these changes
I don't know much about the rocket stages but the parts I did test worked.

2021-12-09 17:33 UTC, dartasen approved these changes
I'll need to rewrite those processors to use metadata system but for now, it looks good

2021-12-10 09:05 UTC, merged