Added UI for custom launch arguments
SubnauticaNitrox/Nitrox pull request #1668
Opened 2021-12-10 10:50 UTC by dartasen

![image](https://user-images.githubusercontent.com/10561268/145561145-29bd12e2-a2d3-4b09-b63a-2d6ab559baf6.png)

2021-12-10 16:33 UTC, Measurity reviewed
As discussed, unrelated to the PR but the toast notifications do not disappear when you hover over with mouse.

2021-12-10 16:33 UTC, Measurity commented on NitroxLauncher/Pages/ServerPage.xaml.cs
> +        public bool IsServerExternal => LauncherLogic.Config.IsExternalServer;
```suggestion
        private bool IsServerExternal => LauncherLogic.Config.IsExternalServer;
```

2021-12-10 16:33 UTC, Measurity commented on NitroxLauncher/Pages/OptionPage.xaml.cs
>          }
```suggestion
        private void ChangeArguments_Click(object sender, RoutedEventArgs e)
        {
            if (string.IsNullOrWhiteSpace(LaunchArguments.Text))
            {
                LaunchArguments.Text = SubnauticaLaunchArguments;
                LauncherNotifier.Error("Invalid launch arguments");
                return;
            }
            
            LaunchArguments.Text = LauncherLogic.Config.SubnauticaLaunchArguments = LaunchArguments.Text.Trim();
            LauncherNotifier.Success("Applied changes");
        }
```

2021-12-10 19:21 UTC, Jannify requested changes

2021-12-10 19:22 UTC, dartasen commented on NitroxLauncher/LauncherLogic.cs
> +                throw new Exception("Location of Subnautica is unknown. Set the path to it in settings.");
Exceptions are shown in a ugly MessageBox like this

![image](https://user-images.githubusercontent.com/10561268/145630094-ed7e6673-9c46-47a9-8d02-baa59dcf378e.png)

2021-12-10 20:19 UTC, dartasen commented
Partial fix for #1657

2021-12-11 11:33 UTC, Measurity requested changes
Let's add a reset button for the launch arguments so people can find their way back if they mess up.

2021-12-11 11:33 UTC, Measurity commented on NitroxLauncher/LauncherConfig.cs
> +                OnPropertyChanged();
Shouldn't property changed also be skipped if `value` is the same as current value?

2021-12-11 11:33 UTC, Measurity commented on NitroxLauncher/LauncherConfig.cs
> +                OnPropertyChanged();
Same here

2021-12-11 21:01 UTC, Measurity approved these changes

2021-12-11 21:02 UTC, merged