Additional help information
SubnauticaNitrox/Nitrox pull request #1690
Opened 2021-12-27 14:08 UTC by Coding-Hen

Cant reopen the old pr due to rebase, pr for reference: 1562

2021-12-28 14:30 UTC, Jannify requested changes

2021-12-28 14:30 UTC, Jannify commented on NitroxServer/ConsoleCommands/WarpCommand.cs
> +            AddParameter(new TypePlayer("name", false, "The players name to teleport too"));
This is not true because of the optional parameter

2021-12-29 22:23 UTC, Jannify approved these changes
Code wise it looks fine 👍

2021-12-29 22:30 UTC, Measurity commented
If you enter help for a command that does not exist it shows this:
![image](https://user-images.githubusercontent.com/1107063/147708083-0113dff2-165b-45cb-ba86-22ae9ed5758f.png)

Would be nicer if it just showed `Command does not exist`.

2021-12-29 23:42 UTC, merged