Improving building system
SubnauticaNitrox/Nitrox pull request #1705
Opened 2022-01-13 17:29 UTC by tornac1234

- [x] Ladders save fix
- [x] Red structures common case fix
- [x] Sign metadata case for Signs
- [ ] (Fix a bug with BaseHatches ?)
- [ ] Need help with testing

I already had a test session with my brother which turned out way better than before. We built lot of things and we didn't encounter any red structure, tho there are still bugs with BaseHatches but I don't know where they come from

2022-01-13 22:45 UTC, Jannify requested changes

2022-01-14 07:18 UTC, tornac1234 commented on NitroxClient/GameLogic/Bases/Spawning/BasePiece/BaseLadderSpawnProcessor.cs
> +            do
what would be the max i then

2022-01-15 10:14 UTC, Jannify commented on NitroxClient/GameLogic/Bases/Spawning/BasePiece/BaseLadderSpawnProcessor.cs
> +            do
As we are speaking of cells there is a max value it can reach. Stored in `NitroxModel_Subnautica.Helper.SubnauticaMap` afair.

2022-02-03 18:41 UTC, tornac1234 commented
Important to note that the command `fastbuild` (which is also executed by the command `bobthebuilder`) may easily cause desyncs

2022-05-16 23:11 UTC, tornac1234 commented
Since the more global PR containing this PR was merged, there's no need for this to stay opened.

2022-05-16 23:11 UTC, closed without merging