Made it more frequent for prefabs to appear
SubnauticaNitrox/Nitrox pull request #1746
Opened 2022-02-24 22:55 UTC by tornac1234

Hotfix for the current issue of player never finding most of the scannable objects spawning around wrecks for example

2022-03-26 12:59 UTC, Jannify requested changes

2022-03-26 12:59 UTC, Jannify commented on NitroxServer/GameLogic/Entities/EntityHelper.cs
> +public abstract class EntityHelper
Isn't an interface more fitting here as it requires to implement the method?

2022-03-26 12:59 UTC, Jannify commented on NitroxServer-Subnautica/GameLogic/Entities/SubnauticaEntityHelper.cs
> +            return nitroxTechType.ToUnity() != TechType.None;
Can't we use `worldEntityInfo.techType != TechType.None` so we don't have a double cast?

2022-03-26 12:59 UTC, Jannify commented on NitroxServer/GameLogic/Entities/Spawning/BatchEntitySpawner.cs
> +        private const float DEFAULT_LUCK_INDICATOR = 0.1f;
As discussed in discord this is not a valid option as the "luck indicator" changes with progression and fragment type afair.

2022-08-08 08:26 UTC, dartasen commented
Since the issue is fixed, we can close this one for now

2022-08-08 08:26 UTC, closed without merging