Fix moonpools undocking not working
SubnauticaNitrox/Nitrox pull request #1747
Opened 2022-02-25 10:48 UTC by tornac1234

There was an error about detecting properly which was the moonpool parent of the VehicleDockingBay

2022-03-26 12:52 UTC, Jannify requested changes

2022-03-26 12:52 UTC, Jannify commented on NitroxClient/GameLogic/Bases/Spawning/BasePiece/BasePieceSpawnProcessor.cs
> +        class BasePieceSpawnInfos
Can this be a private struct?

2022-03-26 12:52 UTC, Jannify commented on NitroxClient/GameLogic/Bases/Spawning/BasePiece/BasePieceSpawnProcessor.cs
> +        public static void ReRunSpawnProcessor(GameObject finishedPiece, NitroxId nitroxId)
Would like to have a comment here when/in what case you need this method

2022-05-14 21:09 UTC, Jannify approved these changes
Code wise seems fine. In-game testing with Ninja didn't show any bugs. Needing one review before merging.

2022-05-14 21:23 UTC, Jannify commented
I have to pull back my approval, I found a few undocking centered errors in the logs:

[22:57:50.284] [ERR] Error processing packet [VehicleUndocking: VehicleId: 2e95079a-40bb-4393-9020-9284103c00a3, DockId: 053d8a55-f6a8-467c-9cdb-c5f509a4842b, PlayerId: 2, UndockingStart: False]
System.NullReferenceException: Object reference not set to an instance of an object
  at NitroxClient.GameLogic.RemotePlayer.SetVehicle (Vehicle newVehicle) [0x000b1] in <4bb7ca7b72d74f11940c27f99df4e928>:0 
  at NitroxClient.Communication.Packets.Processors.VehicleUndockingProcessor.FinishVehicleUndocking (NitroxModel.Packets.VehicleUndocking packet, Vehicle vehicle, VehicleDockingBay vehicleDockingBay) [0x00076] in <4bb7ca7b72d74f11940c27f99df4e928>:0 
  at NitroxClient.Communication.Packets.Processors.VehicleUndockingProcessor.Process (NitroxModel.Packets.VehicleUndocking packet) [0x00051] in <4bb7ca7b72d74f11940c27f99df4e928>:0 
  at NitroxClient.Communication.Packets.Processors.Abstract.ClientPacketProcessor`1[T].ProcessPacket (NitroxModel.Packets.Packet packet, NitroxModel.Packets.Processors.Abstract.IProcessorContext context) [0x00001] in <4bb7ca7b72d74f11940c27f99df4e928>:0 
  at NitroxClient.MonoBehaviours.Multiplayer.ProcessPackets () [0x00055] in <4bb7ca7b72d74f11940c27f99df4e928>:0

2022-05-28 18:23 UTC, tornac1234 commented
I tested it after rebasing and it still worked fine

2022-06-04 10:54 UTC, dartasen approved these changes
From the test session we did, he seems to work pretty well without errors in the logs. We found a bug when trying to dock 2 vehicles at the same time but it's something related to the awful subnautica's code, and it can be fixed by restarting the game.

2022-06-04 11:57 UTC, merged