Combined base fixes.
SubnauticaNitrox/Nitrox pull request #1751
Opened 2022-02-27 11:57 UTC by MrPurple6411

Combined My base stabilization branch with @tornac1234 's #1705 and then corrected some positioning mistakes I had made.

Changes over and above the old PR's
  - Corrected the change construction value to stop doing EXTRA construction on the receiving end.
  - Corrected Base Modules such as bio reactor/Filtration Machine/ACU leaving behind functionality colliders and fx when deconstructed.
  - I removed some Extra Building positional validation that was is truly not required because the position of the object is validated by the client who sent it. Otherwise they would not have been able to send it in the first place.
  - Removing rate limit on construction change packages fixed issue where fastbuild was not working. 
  - Merged Main into branch to bring PR up to date.

2022-03-30 22:22 UTC, Jannify requested changes

2022-03-30 22:22 UTC, Jannify commented on NitroxClient/MonoBehaviours/ThrottledBuilder.cs
> +                    if (cellTransform != null)
```suggestion
                    if (cellTransform)
```

2022-03-30 22:22 UTC, Jannify commented on NitroxClient/MonoBehaviours/ThrottledBuilder.cs
> +                if (placedPiece == null )
```suggestion
                if (!placedPiece)
```

2022-04-01 12:58 UTC, tornac1234 commented on NitroxClient/GameLogic/Bases/Spawning/BasePiece/BaseLadderSpawnProcessor.cs
> +                cellToSearch = new Int3(latestCell.x, latestCell.y + searchOffset, latestCell.z);
Just realized with some tests but maxY is currently 20 tho we're counting in cells and not batches so we can go wayyy further than 20. Therefore we shall want to set a max limit like 200 (= [20 which is DimensionsInBatches.Y] * [10 which is the amount of CellsPerBlock in AbsoluteEntityCell for most levels])

2022-04-09 18:26 UTC, MrPurple6411 commented on NitroxClient/GameLogic/Building.cs
> +        //private float timeSinceLastConstructionChangeEvent;
yes otherwise fastbuild breaks

2022-04-21 00:33 UTC, DV8FromTheWorld commented on NitroxServer-Subnautica/Serialization/SubnauticaServerProtoBufSerializer.cs
> +            rotationData.AddSubType(80, typeof(AnchoredFaceBuilderMetadata));
```suggestion
            MetaType builderMetadata = Model.Add(typeof(BuilderMetadata), false);
            builderMetadata.AddSubType(50, typeof(CorridorBuilderMetadata));
            builderMetadata.AddSubType(60, typeof(MapRoomBuilderMetadata));
            builderMetadata.AddSubType(70, typeof(BaseModuleBuilderMetadata));
            builderMetadata.AddSubType(80, typeof(AnchoredFaceBuilderMetadata));
```

2022-05-14 20:10 UTC, Jannify commented on NitroxModel/Packets/EntityDestroy.cs
> +}
```suggestion
namespace NitroxModel.Packets;

[Serializable]
public class EntityDestroy : Packet
{
    public NitroxId EntityId { get; }

    public EntityDestroy(NitroxId entityId)
    {
        EntityId = entityId;
    }
}
```

2022-05-14 20:14 UTC, Jannify commented on NitroxPatcher/Patches/Dynamic/Constructable_SetState_Patch.cs
> +                // TornacTODO: Check this gameobject to see why it can't be removed its nitrox entity
@tornac1234

2022-05-14 20:17 UTC, Coding-Hen commented
Might be worth removing some of the logging as it clutters up the logs. 
Notibly:
Clearing Base Geometry, storing id for later lookup
When respawning geometry, found face-based id to copy to new object

2022-05-15 13:53 UTC, tornac1234 commented on NitroxPatcher/Patches/Dynamic/Constructable_SetState_Patch.cs
> +                // TornacTODO: Check this gameobject to see why it can't be removed its nitrox entity
I think it's no longer relevant since it was supposed to be yet another way of fixing one of the issues

2022-05-15 13:54 UTC, tornac1234 commented
> Might be worth removing some of the logging as it clutters up the logs. Notibly: Clearing Base Geometry, storing id for later lookup When respawning geometry, found face-based id to copy to new object

Yes also it seems that the most logs you add during geometry respawn, the more lags you'll have when you have bigger bases so we may just want to not log anything during the process (at least in release mode)

2022-05-16 22:44 UTC, dartasen approved these changes
We did a big test session with a complex base, and it's way better than before with a decent amount of error logs

2022-05-16 22:59 UTC, merged