Synced commands concerning aurora
SubnauticaNitrox/Nitrox pull request #1753
Opened 2022-03-01 21:40 UTC by tornac1234

These are the 4 commands:
- ``countdownship`` (will explode aurora as if we were just skipping to the last warning, which means we have the 20s of audio that come with aurora explosion in normal time)
- ``explodeship`` (will explode aurora instantly)
- ``restoreship`` (will restore the base state of aurora and restart all warning countdowns)
- ``explodeforce`` (only shows FX)

We sync all of them except explodeforce which is not worse syncing (tell me if you disagree), tho it is also deactivated.
Also, aurora command can't be executed from the server's console.

- [x] Add aurora's state to the summary (images down there)
- [x] Add a dedicated command on server-side "aurora" for the 3 different actions (explode/restore/countdown)
- [x] Modified EventTriggerer functioning to be able to support restoring Aurora

![image](https://user-images.githubusercontent.com/24827220/156253408-dcf3706c-c766-436b-8da0-5e151109f889.png)
(Will show the number of the next warning to come)
![image](https://user-images.githubusercontent.com/24827220/156253419-b63085e3-dd5b-4e48-95ac-78ea14647fcd.png)

2022-03-09 23:11 UTC, Coding-Hen requested changes
Functionaly seems to work fine. My only comment is with the inconsistent spacing between methods throughout these changes

2022-03-09 23:14 UTC, tornac1234 commented on NitroxPatcher/Patches/Dynamic/CrashedShipExploder_OnConsoleCommand_explodeship_Patch.cs
> +    // This command's purpose is just to show FX, we don't need to sync it
My bad 🤡

2022-03-09 23:17 UTC, tornac1234 commented
I'll commit space changes with rebasing

2022-03-26 13:49 UTC, Jannify commented
Needs rebase

2022-03-26 14:21 UTC, tornac1234 commented
Ready for review / tests

2022-03-26 15:07 UTC, Jannify requested changes

2022-03-26 15:07 UTC, Jannify commented on NitroxServer/GameLogic/EventTriggerer.cs
> +        /// Tell the players to start Aurora's restoration event
```suggestion
        /// Tells the players to start Aurora's restoration event
```

2022-03-26 15:07 UTC, Jannify commented on NitroxServer/GameLogic/EventTriggerer.cs
> +        /// Tell the players to start Aurora's explosion event
```suggestion
        /// Tells the players to start Aurora's explosion event
```

2022-03-26 15:07 UTC, Jannify commented on NitroxServer/GameLogic/EventTriggerer.cs
> +            // The timer interval is in milliseconds, and so the AuroraExplosionTime should be
```suggestion
```
If this is really important the variable should be called auroraExplosionTimeMs and not a "hidden" comment inside the constructor.

2022-03-26 15:07 UTC, Jannify commented on NitroxServer/GameLogic/EventTriggerer.cs
> +        // Necessary to calculate correctly the timers' duration
```suggestion
        // Necessary to calculate the timers correctly
```

2022-04-16 11:36 UTC, Jannify approved these changes
Code wise seems fine

2022-04-30 22:20 UTC, Coding-Hen commented
Will test asap tomorrow when I get home and access to a computer

2022-05-04 22:46 UTC, Coding-Hen approved these changes
Works after in game testing

2022-05-09 09:13 UTC, merged