Migrating ProtoBuf and JSON for data types
SubnauticaNitrox/Nitrox pull request #1954
Opened 2022-12-30 19:27 UTC by Jannify

- Replacing all `ProtoContracts`/`ProtoMembers` with `DataContract`/`DataMembers` which is usable by both ProtoBuf and Json
- Removing unused using directives in solution

2022-12-30 21:37 UTC, Measurity requested changes

2022-12-30 21:37 UTC, Measurity commented on NitroxServer/Serialization/ServerProtoBufSerializer.cs
> +                    Model[type].Add(tag, property.Name);
We can use `is ProtoMemberAttribute protoAttr` to get the tag now, since DLLs are publicized.

2022-12-30 21:37 UTC, Measurity commented on NitroxServer/Serialization/ServerProtoBufSerializer.cs
> +            if (o.GetType().ToString().Contains("ProtoContractAttribute"))
Can use `is ProtoContractAttribute`

2022-12-30 21:37 UTC, Measurity commented on NitroxServer/Serialization/ServerProtoBufSerializer.cs
> +                bool hasNitroxDataContract = type.GetCustomAttributes(typeof(DataContractAttribute), false).Length > 0;
Use inline methods to exit early when the first condition is already true.

```cs
bool HasNitroxProtobuf(Type type) => type.GetCustomAttributes(typeof(ProtoContractAttribute), false).Length > 0;

foreach (Type type in Assembly.Load(assemblyName).GetTypes())
        {
            try
            {
                if (HasNitroxProtobuf(type) || ..)
```

2022-12-30 21:37 UTC, Measurity commented on NitroxServer/Serialization/ServerProtoBufSerializer.cs
> +                    int tag = (int)attributeType.GetProperty("Tag", BindingFlags.Public | BindingFlags.Instance).GetValue(customAttribute, emptyArray);
`emptyArray` can be replaced by `Array.Empty<object>()`.

2022-12-30 21:37 UTC, Measurity commented on NitroxServer/GameLogic/Unlockables/PDAStateData.cs
> +        [DataMember(Order = 6)]
Minor but we might want to reoder the fields to align with `DataMember.Order`

2022-12-30 23:11 UTC, Measurity approved these changes
LGTM :)

2022-12-30 23:36 UTC, Coding-Hen approved these changes
The only concern that I had was the data ordering but from looking at the documentation, it only appears to effect json serialisation ordering and not deserialising.

2022-12-31 11:57 UTC, dartasen commented on NitroxModel/NitroxModel.csproj
> +        <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
I don't think it fits the comment "Polyfill for modern c# lang support"

2023-01-01 16:37 UTC, Measurity approved these changes

2023-01-01 19:35 UTC, merged