Migrating fire over to the new entity system and improving the experience
SubnauticaNitrox/Nitrox pull request #2012
Opened 2023-03-30 04:34 UTC by Sunrunner37

Currently fires in Nitrox are entirely hit and miss.  Players will douse fires in the aurora but the behavior doesn't sync correctly due to prefab spawning issues.  Similarly, fires in the cyclops will spawn about 50% of the time and have no ability to persist after a server reset or reconnect.  The smoke would also hang around for some players.  

This PR migrates fires to the new entity system and deprecates 8 fire-specific classes.

Fires put out after reconnection:

![image](https://user-images.githubusercontent.com/3238547/228729759-142a336f-2855-4d1f-8ac2-b5dfeddd643a.png)

Cooperative fire fighting:

![image](https://user-images.githubusercontent.com/3238547/228729830-05dc3673-ad81-4141-b892-6afb3f669367.png)

Fires in the cyclops:

![image](https://user-images.githubusercontent.com/3238547/228729880-65f394cb-fbc1-4f2f-9c8e-79bf2099e756.png)

Smoke clearing after the fire: 

![image](https://user-images.githubusercontent.com/3238547/228729945-5d22a9a6-4199-4ec2-980a-5db3f52ebe11.png)

2023-04-24 16:23 UTC, dartasen approved these changes

2023-05-06 16:11 UTC, Jannify requested changes
`WorldPersistenceTest` is missing checks for `CyclopsFireEntity` and `FireMetadata`.

2023-05-06 16:11 UTC, Jannify commented on NitroxPatcher/Patches/Dynamic/Fire_Douse_Patch.cs
> +            Log.Error($"Fire instance is unknown to the server {__instance.gameObject.name}");
Server?

2023-05-06 16:11 UTC, Jannify commented on NitroxPatcher/Patches/Dynamic/Fire_Douse_Patch.cs
> +            Resolve<IPacketSender>().Send(new EntityDestroyed(nitroxId));
Is there a chance for race conditions and could it cause problems? Maybe we want to wait a little before deleting the entity?

2023-05-06 16:11 UTC, Jannify commented on NitroxPatcher/Patches/Dynamic/SubFire_CreateFire_Patch.cs
> +                        CyclopsFireEntity cyclopsFireEntity = new((int)startInRoom.roomLinks.room, nodeIndex, fireId, TechType.None.ToDto(), null, subRootId, new());
```suggestion
                        CyclopsFireEntity cyclopsFireEntity = new((int)startInRoom.roomLinks.room, nodeIndex, fireId, NitroxTechType.None, null, subRootId, new());
```

2023-08-05 12:27 UTC, tornac1234 requested changes
Needs rebase, modifications from #2063 (patches) and #1908 (replacing Nitrox.GetId) should be applied.

2023-08-05 12:27 UTC, tornac1234 commented on NitroxClient/GameLogic/Spawning/CyclopsFireEntitySpawner.cs
> +            Fire existingFire = fireTransform.GetComponentInChildren<Fire>();
```suggestion
            Fire existingFire = fireTransform.GetComponentInChildren<Fire>(true);
```

2023-08-05 12:27 UTC, tornac1234 commented on NitroxClient/GameLogic/Spawning/CyclopsFireEntitySpawner.cs
> +            if (existingFire && NitroxEntity.GetId(existingFire.gameObject) != id)
Change ``GetId`` to something more relevant (after rebase)

2023-08-05 12:27 UTC, tornac1234 commented on NitroxClient/GameLogic/Spawning/CyclopsFireEntitySpawner.cs
> +        Fire fire = newFireGameObject.GetComponentInChildren<Fire>();
```suggestion
        Fire fire = newFireGameObject.GetComponentInChildren<Fire>(true);
```

2024-08-22 22:36 UTC, dartasen commented
Will need few rework and rebase to be properly integrated, closing it for now

2024-08-22 22:36 UTC, closed without merging