Allow the server to download a prebaked entity file hosted by nitrox.
SubnauticaNitrox/Nitrox pull request #2021
Opened 2023-04-11 02:13 UTC by Sunrunner37

Currently, Nitrox loads entities as the player moves around the world.  This causes notable lag when a player enters a batch for the first time because the server needs to invoke the batch spawning logic.  The alternative is for the user to enable `CreateFullEntityCache` in the config file, which loads all of the entities ahead of time but causes a significant start-up latency.

This change allows us to host a prebaked save file that contains all of the parsed entity data (identified as `BAKED`).  The previous functionality is still available under the modes `STREAMING` and `UPFRONT`.  Developers will leverage streaming by default because it is easier on the hard disk. We can host a dev only baked file that is empty to test features that do not require spawning.  The release build will always use baked because it is the ideal user experience.  

As a follow-up, I will disable all of the unneeded resource parsing when using a baked world. Additionally, I will switch prefab parsing back to single threaded.  However, these optimizations are stand alone improvements.

2023-04-15 12:07 UTC, Jannify requested changes

2023-04-15 12:07 UTC, Jannify commented on NitroxServer/Serialization/World/WorldManager.cs
> +            new ServerProtoBufSerializer().Serialize(Path.Combine(saveDir, $"Version.nitrox"), new SaveFileVersion());
Shouldn't we use the created Serializers by AutoFac here?

2023-04-15 12:07 UTC, Jannify commented on NitroxServer/Serialization/World/WorldPersistence.cs
> +            Log.Info($"Extracting prebaked save into {savePath}");
```suggestion
            Log.Info($"Extracted prebaked save into {savePath}");
```

2024-01-27 14:04 UTC, dartasen commented
Closing it for now, it's likely we won't go in that direction for now

2024-01-27 14:04 UTC, closed without merging