Sync name and colors for vehicles, rocket and cyclops
SubnauticaNitrox/Nitrox pull request #2090
Opened 2023-10-29 10:32 UTC by tornac1234

- [x] When an entity is updated, ensure its children are also updated
- [x] Fix, improve and implement name and colors sync/persistence for vehicles, rocket and cyclops

2023-11-22 20:06 UTC, Jannify requested changes

2023-11-27 21:20 UTC, Jannify requested changes
WorldPersistenceTest is failing for me, ExosuitMetadata Has no equality entry

2023-12-02 18:19 UTC, tornac1234 commented on NitroxModel/DataStructures/GameLogic/Entities/Metadata/EntityMetadata.cs
> +    [ProtoInclude(290, typeof(NamedColoredMetadata))]
Change numbers to 50+n cf https://github.com/SubnauticaNitrox/Nitrox/pull/2087#discussion_r1409719990

2023-12-17 13:05 UTC, Measurity approved these changes

2023-12-17 13:24 UTC, tornac1234 commented
Force pushed required changes and master rebase

2023-12-18 11:39 UTC, dartasen approved these changes

2023-12-18 11:50 UTC, Jannify approved these changes

2023-12-18 11:57 UTC, merged