Add basic sync for PvP
SubnauticaNitrox/Nitrox pull request #2107
Opened 2024-01-10 19:54 UTC by tornac1234

- [x] Basic sync for PvP (only allowed with knifes and heatblades for now)
- [ ] Maybe: add sync for propulsion and repulsion cannon

To be tested (and merged) upon #2106 (won't work without it)

2024-01-29 12:02 UTC, ywgATustcbbs commented
is there really one who likes pvp in Subnautica? if one wants pvp, why not go ahead to play pvp games? there are tons of such games. i don't think core players of Subnautica wants to pvp.

2024-01-29 12:33 UTC, NinjaPedroX commented
> is there really one who likes pvp in Subnautica? if one wants pvp, why not go ahead to play pvp games? there are tons of such games. i don't think core players of Subnautica are interested in pvp.

Most multiplayer games have ways for players to damage each other. Even if it's not the main focus of the game, it gives players more options to have fun with their friends. Having a last man standing battle within a large base or picking people up and repelling them far away with the propulsion cannon is the kind of thing people (like myself) like to do with our friends. I don't think the argument of "if you want to do PvP, play a PvP game" is a good reason to stop this.

Besides, you can just turn PvP off in the configs if you don't want it.

2024-04-29 08:36 UTC, tornac1234 commented
Waiting for #2106 to be merged, then this will get some tests and will be ready to be merged

2024-09-24 19:24 UTC, Jannify requested changes

2025-01-05 10:05 UTC, tornac1234 commented on NitroxClient/Communication/Packets/Processors/PvPAttackProcessor.cs
> +        if (Player.main && Player.main.liveMixin)
If local player isn't instantiated, or its live mixin isn't found, then it can only mean that the game is an early loading state/in an unloading state in whih case it's not necessary to log the failure

2025-01-05 11:05 UTC, Measurity requested changes
CW review

2025-01-05 11:05 UTC, Measurity commented on NitroxPatcher/Patches/Dynamic/LiveMixin_TakeDamage_Patch.cs
> +        if (dealer == Player.mainObject && Inventory.main.GetHeldObject())
Would invert the if statement to reduce cognitive load.

2025-01-05 11:05 UTC, Measurity commented on NitroxServer/Communication/Packets/Processors/PvPAttackProcessor.cs
> +        }
The if statement is doing too much so would split it up.

```suggestion
        if (!serverConfig.PvPEnabled)
        {
            return;
        }
        if (!playerManager.TryGetPlayerById(packet.TargetPlayerId, out Player targetPlayer))
        {
            return;
        }
        if (!damageMultiplierByType.TryGetValue(packet.Type, out float multiplier))
        {
            return;
        }
        packet.Damage *= multiplier;
        targetPlayer.SendPacket(packet);
```

2025-01-05 11:19 UTC, Measurity commented
Works for me so after code changes are done I'll approve.

2025-01-05 13:45 UTC, Measurity approved these changes
:+1:

2025-01-05 13:51 UTC, Measurity approved these changes
Tests still work so LGTM

2025-01-05 14:14 UTC, Coding-Hen requested changes

2025-01-05 14:14 UTC, Coding-Hen commented on NitroxServer/Communication/Packets/Processors/PvPAttackProcessor.cs
> +        { PvPAttack.AttackType.KnifeHit, 0.5f },
Why do we need a multiplier and not just use the base value of the weapon?

2025-01-05 14:14 UTC, Coding-Hen commented on NitroxServer/Communication/Packets/Processors/PvPAttackProcessor.cs
> +    // TODO: In the future, do a whole config for damage sources
Should we create a ticket to add in the other sources if we know what they are so they don't get forgotten?

2025-01-05 14:16 UTC, Measurity commented on NitroxServer/Communication/Packets/Processors/PvPAttackProcessor.cs
> +        { PvPAttack.AttackType.KnifeHit, 0.5f },
I think it makes sense to reduce the damage of starter weapon so new players can ease into Pvp accidents.

2025-01-05 14:19 UTC, Coding-Hen commented on NitroxServer/Communication/Packets/Processors/PvPAttackProcessor.cs
> +        { PvPAttack.AttackType.KnifeHit, 0.5f },
Yeah makes sense. I think having that config Todo created then for future would be good for players to configure but for now this is a good start to the pvp sync

2025-01-05 14:32 UTC, Coding-Hen approved these changes

2025-01-05 15:28 UTC, NinjaPedroX commented
Would it be a good idea to maybe add a `/pvp on/off` console command so that it can be enabled or disabled while players are in game? (Instead of having to restart the server to change the setting)

2025-01-05 16:02 UTC, tornac1234 commented
I believe a server config is not meant to be modified at play time and this kind of option should be thought about before starting a server. But I'd like to hear about others' opinions

2025-01-05 16:22 UTC, NinjaPedroX commented
> I believe a server config is not meant to be modified at play time and this kind of option should be thought about before starting a server. But I'd like to hear about others' opinions

Isn't the gamemode config setting modified during play time with the `/changeservergamemode mode` command? The possible keepInventory setting would also make sense to be changeable in-game when that gets implemented

2025-01-05 16:26 UTC, Coding-Hen commented
I could see an argument for both a command and not. I don't think if it's hard to add an option for it then we shouldn't but if it's going to be hard then maybe just a server setting in the config for now will do

2025-01-05 17:52 UTC, Jannify approved these changes

2025-01-05 18:38 UTC, tornac1234 commented
Will add a "pvp on/off" command

2025-01-05 19:48 UTC, Coding-Hen commented on NitroxServer/ConsoleCommands/PvpCommand.cs
> +        using (serverConfig.Update(Path.Combine(WorldManager.SavesFolderDir, serverConfig.SaveName)))
Probably not for this PR but I feel like we shouldn't have to specify this whole thing in the command and should just be able to call severconfig.update()

2025-01-05 19:56 UTC, Measurity commented on NitroxServer/ConsoleCommands/PvpCommand.cs
> +        using (serverConfig.Update(Path.Combine(WorldManager.SavesFolderDir, serverConfig.SaveName)))
Side effect of how bad the DI in server is setup right now, but issue is created for it: #2166

2025-01-05 20:26 UTC, merged