Modify teleport to move vehicle
SubnauticaNitrox/Nitrox pull request #2111
Opened 2024-01-17 21:41 UTC by MistaOmega

Attempting to modify the vehicle teleport behaviour.

Correctly updates player pos with player in seamoth / prawn

2024-05-16 10:26 UTC, Jannify requested changes

2024-05-16 10:26 UTC, Jannify commented on NitroxClient/Communication/Packets/Processors/PlayerTeleportedProcessor.cs
> +                // Freeze the player while he's loading its new position
```suggestion
```

2024-05-16 10:26 UTC, Jannify commented on NitroxClient/Communication/Packets/Processors/PlayerTeleportedProcessor.cs
> +            currentVehicle.TeleportVehicle(packet.DestinationTo.ToUnity(), currentVehicle.transform.rotation);
For clarity I would do an early return, so:
```
        // Check to make sure the player is in a vehicle
        if (currentVehicle != null)
        {
            currentVehicle.TeleportVehicle(packet.DestinationTo.ToUnity(), currentVehicle.transform.rotation);
            return;
        }

        Player.main.SetPosition(packet.DestinationTo.ToUnity());
```

2024-05-16 10:26 UTC, Jannify commented on NitroxClient/Communication/Packets/Processors/PlayerTeleportedProcessor.cs
> +        if (currentVehicle != null)
It's heavily advised to not check unity components and gameobjects against null. Instead just handle the object as a bool. 
```suggestion
        if (currentVehicle)
```
See: https://discussions.unity.com/t/how-can-i-check-if-an-object-is-null/23224/4

2024-05-16 10:26 UTC, Jannify commented on NitroxPatcher/Patches/Dynamic/GoTo_Patch.cs
> +        if (currentMountedVehicle == null)
Same here with checking against null 
```suggestion
        if (!currentMountedVehicle)
```

2024-05-16 10:26 UTC, Jannify commented on NitroxPatcher/Patches/Dynamic/GoTo_Patch.cs
> +    public static readonly MethodInfo TARGET_METHOD = Reflect.Method((GotoConsoleCommand gotoConsoleCommand) => gotoConsoleCommand.GotoPosition(default, default));
Minor, just bc other patched have it this way:
```suggestion
    public static readonly MethodInfo TARGET_METHOD = Reflect.Method((GotoConsoleCommand t) => t.GotoPosition(default, default));
```

2024-05-16 10:26 UTC, Jannify commented on NitroxPatcher/Patches/Dynamic/GoTo_Patch.cs
> +using HarmonyLib;
```suggestion
```

2024-05-16 10:26 UTC, Jannify commented on NitroxPatcher/Patches/Dynamic/GoTo_Patch.cs
> +public sealed partial class GoTo_Patch : NitroxPatch, IDynamicPatch
Patches are named like: `<PatchedClass>_<PatchedMethod>_Patch.cs`. Could you rename the file and class in this fashion?

2024-09-24 18:38 UTC, Jannify commented on NitroxPatcher/Patches/Dynamic/GotoConsoleCommand_GotoPosition_Patch.cs
> +    public static bool Prefix(Vector3 position, bool gotoImmediate = false)
You don't need to include the parameters if you don't need them.
```suggestion
    public static bool Prefix(Vector3 position)
```

2024-09-24 18:39 UTC, Jannify approved these changes
Except the one comment LGTM CW

2024-11-18 00:26 UTC, tornac1234 requested changes
This PR is lacking a feature which is allowing the warpforward command to also work with vehicles as well

Also please apply a rebase to this branch so you can test it with the latest movement PR merged

2024-12-09 20:13 UTC, Jannify requested changes

2024-12-09 20:13 UTC, Jannify commented on NitroxPatcher/Patches/Dynamic/Player_WarpForward_Patch.cs
> +        if (__instance.currentMountedVehicle == null)
```suggestion
        if (!__instance.currentMountedVehicle)
```
You should not use null checks against unity engine objects (see [here](https://docs.unity3d.com/6000.0/Documentation/Manual/null-reference-exception.html))

2024-12-12 08:36 UTC, Coding-Hen requested changes

2024-12-12 08:36 UTC, Coding-Hen commented on NitroxClient/Communication/Packets/Processors/PlayerTeleportedProcessor.cs
> +                Vector3 position = subRoot.transform.rotation * packet.DestinationTo.ToUnity() + subRoot.transform.position;
Do we not want to keep the brackets here just for clarity of the order we expect? (I know bidmas does this in the background technically)

2024-12-12 08:36 UTC, Coding-Hen commented on NitroxPatcher/Patches/Dynamic/GotoConsoleCommand_GotoPosition_Patch.cs
> +        currentMountedVehicle.TeleportVehicle(position, currentMountedVehicle.transform.rotation); // handle GoTo with a vehicle teleport, which takes player too
```suggestion
        currentMountedVehicle.TeleportVehicle(position, currentMountedVehicle.transform.rotation); // Handle GoTo with a vehicle teleport, which takes player too
```

2024-12-12 08:36 UTC, Coding-Hen commented on NitroxPatcher/Patches/Dynamic/Player_WarpForward_Patch.cs
> +        Vector3 newPosition = __instance.transform.position + __instance.camRoot.GetAimingTransform().forward * num;
If this is the intended 
```suggestion
        Vector3 newPosition = __instance.transform.position + (__instance.camRoot.GetAimingTransform().forward * num);
```

2024-12-19 07:17 UTC, Coding-Hen approved these changes

2024-12-20 19:56 UTC, Jannify approved these changes
LGTM CW

2025-01-05 18:21 UTC, Jannify commented
Needs rebase and review from @tornac1234

2025-01-12 12:09 UTC, Measurity commented on NitroxPatcher/Patches/Dynamic/Player_WarpForward_Patch.cs
> +        }
This if check would be better checked first (before calculating stuff)

2025-01-12 12:31 UTC, tornac1234 commented
Squashed for simplicity, rebased and applied some modifications.

2025-01-12 12:32 UTC, tornac1234 approved these changes

2025-01-13 17:26 UTC, Gauvino commented
Just tested this PR and no longer problem with the seamoth

2025-01-13 17:27 UTC, Gauvino approved these changes
From ingame testing it's good

2025-01-14 01:08 UTC, Jannify requested changes

2025-01-14 01:08 UTC, Jannify commented on NitroxPatcher/Patches/Dynamic/Player_WarpForward_Patch.cs
> +
```suggestion
```

2025-02-08 21:21 UTC, tornac1234 approved these changes

2025-02-09 17:19 UTC, dartasen approved these changes

2025-02-09 18:19 UTC, Jannify approved these changes

2025-02-09 19:03 UTC, merged