Enable "First Use Cinematics" on EscapePod
SubnauticaNitrox/Nitrox pull request #2216
Opened 2024-12-30 16:51 UTC by dartasen

First time that a player will join a game, we'll toggle first use cinematics on escape pods hatches

* Known limitation : player that instant reconnect will never have those cinematics

2024-12-30 19:56 UTC, Jannify requested changes

2024-12-30 19:56 UTC, Jannify commented on NitroxPatcher/Patches/Persistent/EscapePodFirstUseCinematicsController_Initialize_Patch.cs
> +public sealed partial class EscapePodFirstUseCinematicsController_OnSceneObjectsLoaded_Patch : NitroxPatch, IPersistentPatch
The file is still named like the old patch

2024-12-30 22:01 UTC, Jannify approved these changes
LGTM CW

2025-01-05 01:46 UTC, Jannify requested changes

2025-01-05 01:46 UTC, Jannify commented on NitroxClient/GameLogic/InitialSync/PlayerInitialSyncProcessor.cs
> +            // Call code we suppressed inside EscapePodFirstUseCinematicsController_Initialize_Patch
```suggestion
            // Call code we suppressed inside EscapePodFirstUseCinematicsController_OnSceneObjectsLoaded_Patch
```

2025-01-05 23:05 UTC, Coding-Hen approved these changes
LGTM

2025-01-05 23:35 UTC, Jannify approved these changes

2025-01-11 23:14 UTC, Jannify commented
Needs rebase :)

2025-01-12 22:42 UTC, Jannify approved these changes

2025-01-12 22:47 UTC, tornac1234 commented
I question the fact that this spawns unsynced entities. Shouldn't we do something about it or do we not care ?

2025-01-12 22:50 UTC, dartasen commented
> I question the fact that this spawns unsynced entities. Shouldn't we do something about it or do we not care ?

Can open a ticket to pin that "issue", did not find any elegant solution yet

2025-01-12 23:11 UTC, Coding-Hen approved these changes

2025-01-12 23:47 UTC, dartasen commented
Added a transpiler to kill entities at the end of the cinematics, and created a ticket @Jannify @tornac1234.

2025-01-13 00:35 UTC, Jannify requested changes

2025-01-13 00:35 UTC, Jannify commented on NitroxPatcher/Patches/Dynamic/EscapePodFirstUseCinematicsController_ReleaseCreature_Patch.cs
> +        return false;
```suggestion
        if (creatureGO)
        {
            UnityEngine.Object.Destroy(creatureGO);
        }

        return false;
```

2025-01-13 00:43 UTC, tornac1234 reviewed
LGTM CW HAT TPR ?

2025-01-13 00:44 UTC, tornac1234 approved these changes

2025-01-13 00:45 UTC, dartasen commented
Y IHT TPR

![image](https://github.com/user-attachments/assets/a9b4a3c7-e31d-420a-8515-cfacc037667f)

2025-01-13 01:28 UTC, Jannify approved these changes
LGTM CW GT YHT TPR

2025-01-13 07:18 UTC, Coding-Hen approved these changes
LGTM

2025-01-13 09:23 UTC, merged